# ACCOUNTS FORMS VARIABLES
ACCOUNT_ALREADY_EXIST_EMAIL = 'This email is already registered.'
ACCOUNT_PASSWORD_NOT_MATCHING = 'The password is not matching.'
ACCOUNT_EMAIL_NOT_REGISTERED = 'This email is not registered.'
ACCOUNT_INCORRECT_PASSWORD = 'The password is incorrect.'
ACCOUNT_PASSWORD_REQUIRED = 'Password is Required.'
ACCOUNT_REGISTER_SUCCESS = 'Successfully registered.'
ACCOUNT_MODEL_BACKEND = 'django.contrib.auth.backends.ModelBackend'
ACCOUNT_LOGIN_SUCCESS = 'Successfully logged in.'
ACCOUNT_LOGIN_FAILED = 'Invalid credentials.'
ACCOUNT_LOGOUT_SUCCESS = 'Successfully logged out.'
ACCOUNT_EMAIL_NOT_VERIFIED = 'The email is not verified.'
ACCOUNT_PROFILE_IMAGE_LABEL = 'Profile Image'
ACCOUNT_PROFILE_IMAGE_ERROR = 'Profile image should be image file only.'
ACCOUNT_USER_PROFILE_SUCCESS = 'Profile updated.'
# ACCOUNTS TEMPLATE PATH VARIABLE
ACCOUNT_LOGIN_PAGE = 'account/login.html'
ACCOUNT_REGISTER_PAGE = 'account/register.html'
ACCOUNT_USER_PROFILE_PAGE = 'account/'
ACCOUNT_EMAIL_HELP_TEXT = 'Example: useremail@gmail.com'
ACCOUNT_PASSWORD_1_HELP_TEXT = 'Password must have one small letter, one capital letter, one number and one special character. Minimum password length is 7.'
